### ISSUE TITLE
Rockets

### ISSUE THREAD

**Issue by Cydhra** [Cydhra/Technocracy#10]
A multistructure, modular rocket system is considered a core feature for tc-astronautics. There currently exists an API for recognizing template structures. This is used to verify the correct assembly of rocket multistructures.
- The rockets consist of multiple modules that are of similar shape but differ in their core blocks and functionality (propulsion, fuel tanks, storage space, player seats, etc...)
- the modules are stacked on top of each other and on rocket start (discussion about details required) the rocket is converted into an entity and flys away.
- the rocket is constructed on a platform made for that purpose. This platform is also a multiblock structure.
- simple rocket parts get detroyed after their use, more expensive may return after a while to the platform. Discussion about details required.
- player modules are not to be implemented yet, since space travel is not a feature of the first release. The code should just be expandable to such modules.

- [x] Rocket Building Blocks
- [x] Rocket Module Templates
- [x] Rocket assembly verification
- [x] Rocket conversion to entity and flying
- [x] Rocket ownership
- ~~Rocket turnaround logic~~ (postponed until astronautics update)
- [x] Rocket logic like fueling, storage and fuel consumption

**Comment by Cydhra** [comment]
6c245c34d655287b000c1cef79f2e763afee087a and following add basic blocks for rocket buildup. Next, rocket module templates should be created and then the rocket entity should be implemented. When that's done and rocket entity ownership has been solved, satellites can finally be finished.

**Comment by Cydhra** [comment]
Features are implemented. Currently missing:
- [ ] Rocket shouldn't fly without fuel
- [x] Guis for rocket and controller
- [ ] Models for rocket thruster and tip
- [ ] unlink rocket from controller immediatly after ignition to prevent exploits

maybe also:
deconstruct rocket via controller
