### ISSUE TITLE
Textures

### ISSUE THREAD

**Issue by Cydhra** [Cydhra/Technocracy#11]
Currently, many textures in the mod are placeholders or experimental textures. We require additional textures for most items and some multiblock structures. Furthermore, it should be discussed whether to use 16 by 16 pixels or 32 by 32 pixels (breaking the default look of minecraft).

**Comment by reichertdavid** [comment]
## Following technocracy textures are sill missing:

- [x] textures/item/silicon_chloride.png
- [x] textures/item/polyfibre.png
- [x] textures/block/lead_glass.png
- [x] textures/item/coil.png
- [x] textures/item/biphenyl.png
- [x] textures/item/membrane.png
- [x] textures/item/servo.png
- [x] textures/block/lead_glass_top.png
- [x] textures/item/upgrade_frame.png
- [x] textures/item/fan.png
- [ ] textures/item/upgrade_machine_energy_4.png
- [ ] textures/item/upgrade_machine_speed_1.png
- [ ] textures/item/upgrade_machine_lubricant.png
- [ ] textures/item/upgrade_machine_add_speed_1.png
- [ ] textures/block/saline_heated_wall_top.png
- [ ] textures/item/upgrade_machine_energy_2.png
- [ ] textures/item/upgrade_machine_speed_2.png
- [ ] textures/item/upgrade_machine_speed_4.png
- [ ] textures/item/upgrade_machine_cooler.png
- [ ] textures/item/upgrade_machine_add_energy_1.png
- [ ] textures/item/upgrade_machine_add_speed_2.png
- [ ] textures/item/upgrade_machine_energy_1.png
- [ ] textures/item/upgrade_machine_speed_3.png
- [ ] textures/item/upgrade_machine_energy_3.png
- [ ] textures/block/saline_controller.png
- [ ] textures/item/upgrade_machine_add_energy_2.png

**Comment by Cydhra** [comment]
Some of the multiblocks could need more CTM textures, as mentioned in #9 
Especially Frame Glass textures.
Someone should find all multiblock textures that would profit from CTM.

**Comment by Cydhra** [comment]
A lot of the machines fallback to default empty machine textures. So alot of machines still need unique front/top/side textures
