### ISSUE TITLE
Basic Machines and Recipes

### ISSUE THREAD

**Issue by Cydhra** [Cydhra/Technocracy#12]
The basic machines of the game must be finalized. A lot of work already has been done, this issue is for tracking further actions and discussion. Recipes for different items and the machines can also be discussed here.

- [x] Pulverizer
- [x] Electrical Furnace
- [x] Chemical Reaction Chamber
- [x] Chemical Processing Chamber
- [x] Alloy Smeltery
- [x] Centrifuge
- [x] Chemical Oxidizing Chamber
- [x] Chemical Etching Chamber
- [x] Crystallization Chamber
- [x] Pyrolysis Kiln
- [x] Compactor
- [x] Electrolysis Chamber
- [x] Polymerisation Chamber
- [x] Crystallization Chamber

Furthermore:
- [x] Machine Recipes
- [x] Redstone Mode Logic
- ~~Redstone Output Logic (further discussion required)~~
- [x] Balance processing costs using the tier system

Also:
- [x] Think of a way to create Salt (spawning? condensing?)
- [x] Discuss ways to produce certain items of Vanilla Minecraft that are not farmable to create more uses for foundation

**Comment by Cydhra** [comment]
The machines were divided into different tiers. Those tiers do not have direct effect on gameplay, however, they decide which machine can be crafted with wich complex parts, so no machine requires items for its recipe that cannot be created without the machine.

![grafik](https://user-images.githubusercontent.com/14911966/63579677-78db1980-c593-11e9-935c-bd6dc3793c6c.png)

This is just a rough outline which can be worked upon. The player should not notice this tier system.

**Comment by Cydhra** [comment]
Discussion showed, that output of redstone signals is (currently) not wanted. Structures like tanks, reactors etc may do that in the future, but not in current milestone.

**Comment by Cydhra** [comment]
Balanced machine energy cost in 575e38127052f0b6f73423225ceeaecc108bbf77
Recipe cost balancing, etc must be done while or after Beta testing, because it needs actual playtesting to verify cost-to-fun-ratios.

**Comment by Cydhra** [comment]
All basic machines and all basic behaviour is implemented.
- Machine Upgrades are missing, but that is not considered important for beta.
- Side configs have problems, but this will be considered when they are actually configurable from GUI
- The Laser Drill is not implemented, however this is part of another issue
- Heat/Cooling Logic is not implemented, however this is not considered important for beta. This will be an enhancement later on
