### ISSUE TITLE
Laser Drills

### ISSUE THREAD

**Issue by Cydhra** [Cydhra/Technocracy#15]
Steal the laser drills of _MineFactory_ and balance them by
- reducing the amount of different ores mineable to 2-4 per dimension
- increasing the amount of energy required drastically

- [ ] Implement Laser Rendering
- [x] Implement Laser Capabilities
- [ ] Implement Laser Logic
- [ ] Implement Laser Emitter
- [x] Implement Laser Drill (as an absorber)

**Comment by Cydhra** [comment]
- [ ] Implement Laser Rendering
- [ ] Implement Laser Capabilities
- [ ] Implement Laser Logic
- [ ] Implement Laser Emitter
- [ ] Implement Laser Drill (as an absorber)
