### ISSUE TITLE
Expandable Storage Options

### ISSUE THREAD

**Issue by Cydhra** [Cydhra/Technocracy#28]
Multi-Block structures for large scale fluid and energy storage are required. Small-

- [x] Multi-Block Capacitor ~~(should be usable as a single block as well)~~
- [x] Multi-Block Tank
- [x] Single-block fluid tank (something like barrels)

**Comment by tth05** [comment]
Should those tanks be able to have weird shapes like the energy cells from EnderIO?
Also any idea capacity wise?

For design ideas I guess the fluid tank is just a frame and glass to fill it, with inlets, outlets, etc.
Not sure about the capacitor... I guess it should have solid walls but be filled with some sort of energy block. What might be even cooler would be if the multi block capacitor was like a Lead–acid battery, and would also like look it. The capacity would be a bit unrealistic but it would be something different from other mods.

**Comment by Cydhra** [comment]
Yes, the idea about the fluid MB-structure seems valid.
for the capacitor I would have done a homogeneous structure, so single-block is also possible. But the idea to have more complex design closer to real-life capacitors is also great.

**Comment by tth05** [comment]
Decided to use the following design ![this](https://user-images.githubusercontent.com/36999320/63183320-fa432100-c054-11e9-800f-78afa9db0154.png)
Basically a simplified version of a [lead-acid battery](https://en.wikipedia.org/wiki/Lead%E2%80%93acid_battery). The pink blocks in the top layer are connectors that connect the electrodes with each other. They can be replaced with energy ports in whatever combination you want.
The empty space has to be filled with sulfuric acid and electrodes are not allowed to touch each other or touch the housing. The controller can be placed anywhere in the sides.

**Comment by Cydhra** [comment]
Could this potentially feature more than two electrodes?

**Comment by tth05** [comment]
Yes, max size is currently 20x20 (just a placeholder) and you can put as much electrodes in it as possible.
I'd need advice on what capacity to give based on the amount of electrodes and height of those. Probably some basic formula would be sufficient.

**Comment by Cydhra** [comment]
I'll think of something

**Comment by Cydhra** [comment]
Summary of our prior discussion:
- The amount of electrodes shall determine the rate at which energy can be transfered from and to the storage. This way, a storage that quickly buffers large spikes in energy or can counter quick energy supply drops, is build using many electrodes.
- The size of the storage divided by the amount of electrode blocks determines the overall capacity of the storage. This way, a storage with large capacity is build with only few electrodes.
- The two electrode types (lead and lead-oxide) are paired with connectors and redstone ports in the hull. Furthermore, no two electrodes of the same type can be adjacent within the same row or column. 

The formulas to calculate the stats will be those for now:

```
avgDistanceSq = average squared distance of each interior block of the structure from its nearest electrode block.
capacity = sqrt(avgDistanceSq) * 512000 * total interior volume / number of electrode blocks
transfer_speed = 300 * number of electrode blocks
```

Beware, that the number of total electrode blocks, not only the number of electrodes is counted. The constant factors might have to be adjusted to account for this.

Additionally the constant factors will later be configurable.

**Comment by Cydhra** [comment]
After reconsideration and discussion we changed the formulas, so the energy storage scales more controllable: Loss of capacity with increasing number of electrodes was reduced and gain of transfer speeds was increased accordingly.

New formulas:
```
capacity = sqrt(avgDistanceSq) * 512000 * total interior volume / sqrt(2 * number of electrode blocks)
transfer_speed = 200 * (number of electrode blocks)²
```

**Comment by Cydhra** [comment]
After reconsideration and discussion we changed the formulas, so the energy storage scales more controllable: Loss of capacity with increasing number of electrodes was reduced and gain of transfer speeds was increased accordingly.

New formulas:
```
capacity = sqrt(avgDistanceSq) * 512000 * total interior volume / sqrt(2 * number of electrode blocks)
transfer_speed = 200 * (number of electrode blocks)²
```

**Comment by Cydhra** [comment]
After reconsideration and discussion we changed the formulas, so the energy storage scales more controllable: Loss of capacity with increasing number of electrodes was reduced and gain of transfer speeds was increased accordingly.

New formulas:
```
capacity = sqrt(avgDistanceSq) * 512000 * total interior volume / sqrt(2 * number of electrode blocks)
transfer_speed = 200 * (number of electrode blocks)²
```

**Comment by Cydhra** [comment]
So only a tank structure is missing. Compared to the capacitor this should be easy, as there is no engineering mechanic to be hidden here: The tank just grows in capacity with its size and does not limit input and output.
A mechanic to incentivize players to build complex tanks does not make much sense, especially because a player likely will need multiple tanks for different fluids anyway.

Note: Drums are rather big in capacity (which may or may not be adjusted in QA), but they cannot be automated, which is the reason players will need a multiblock structure.

The tank should have optional windows, multiple inlets and outlets (possibly on all sides?), and it should only have a controller if this is strictly necessary. If we can avoid adding a controller block, that'd be great.

Futhermore, it should be discussed whether we want a more expensive, but more space efficient version of the tank structure.

**Comment by Cydhra** [comment]
With the addition of the tank - done
