### ISSUE TITLE
Conduits

### ISSUE THREAD

**Issue by Cydhra** [Cydhra/Technocracy#29]
An ambitious conduit network system is considered core-feature.

I got stuck within the network branch, I think I'll give it another shot on a fresh branch. After all, this is the purpose of doing stuff on a branch, isn't it? :P
I will structure my work better this time:

- [x] Remove the remaining network code that is currently on the master branch
- [x] Prepare a model for chunk based network partitions that offers methods for modification. Make sure, the model instances can be loaded and unloaded. Prevent memory leaks.
- [x] Add Nodes to the node network within the chunk. Add all nodes and edges in an orderly fashion and make sure, edge cases work. Make sure pipe types work.
- - [x] Implementation adding pipes
- - [x] Implementation removing pipes
- - [x] Implementation edges
- - [x] Testing
- [x] Serialize the node network to the chunk and load it again. Make sure adding and removing nodes works properly.
- - [x] Serialization
- - [x] Deserialization
- - [x] Testing
- [x] Insert transit sinks into the network.
- - [x] Insertion
- - [x] Deletion
- - [x] Serialization
- [x] Calculate the transit network within a chunk and expose the transit nodes in a special interface. Find a way to advertise reachable sinks within the transit network
- - [x] Calculate shortest paths for transit nodes
- - ~~Advertise sinks within a chunk to the network~~
- - [x] Make sure the transit network is only updated once, if multiple changes to the conduit network happen at once.
- [x] Serialize the transit network to the chunk and load it again. Make sure decomposing, merging, adding and removing nodes works properly.
- [x] Implement routing and flow strategies that span multiple chunks. ~~Cache routes and reuse them, until a chunk gets invalid or the strategy requires a new route.~~
- [x] Offer a model of the network, so the rendering can adapt
- [x] Merge into master
- [ ] ~~Implement pipe tiers~~ Implement Pipe Upgrades and Filters
- ~~Optional: Use a max-flow approach to evaluate how much can be transferred at once~~
- [x] Change pipe recipes to account for pipe types being yanked from features.
- [x] #73
- [ ] #76

More requirements can be discussed here.

**Comment by Cydhra** [comment]
Progress of the conduit network is done on branch "network"

**Comment by Cydhra** [comment]
I've changed the top issue checklist. Ignore the old network branch, the "conduits" branch is the new implementation.

**Comment by Cydhra** [comment]
Inserting sinks into the network is problematic when a pipe already exists and a machine is placed next to it: our tile entities do not fire an update event to neighboring blocks

**Comment by Cydhra** [comment]
The conduits branch has been merged into master. I consider code and API to be stable enough - so no further rewrite of the whole branch is required. The merge is more convenient, as major changes to master (like removing the monolith module) destablelized the branch.
I removed "Advertise sinks within a chunk to the network" from the list, as this is rather useless, as chunks must be traversed by routing in order to find subsequent chunks anyway.

**Comment by Cydhra** [comment]
82ee64f44eb8597d51b8d60353a41d17a36dab91 fixed the problem with update events

**Comment by Cydhra** [comment]
Remaining tasks for path finding:

- [x] delegate sink cooldowns to pipes
- [ ] delegate sink limits to pipe-machine-interfaces
- ~~add support for pipe transmission limits by saving the limits as past costs~~
- ~~add multiple pipe tiers~~

**Comment by Cydhra** [comment]
Change of plans:
- No pipe tiers
- Instead upgrades for pipe-machine-interfaces. They increase transfer speed and can include filters.
- Pipes have unlimited transfer speed, only the interfaces limit the transfer rates.

This makes flow calculation obsolete, makes pipe tiers obsolete and eases usability for players, as they can upgrade an entire network at the producers, and ignore connecting pipes and sinks.
