### ISSUE TITLE
GUI refinement

### ISSUE THREAD

**Issue by Cydhra** [Cydhra/Technocracy#36]
Refine the optics of GUI screens by using non-placeholder graphics for fluid-/energy bars, tab icons, progress bars, etc.

- [x] finalized content-bar textures
- [ ] finalzed progress-bar textures
- [ ] finalized configuration tab layouts (side, redstone mode, etc)
- [ ] finalized tab icons
- [ ] #72
- [ ] everything has tool tips
