### ISSUE TITLE
Multiplayer/Non-Dev-Environment Issues

### ISSUE THREAD

**Issue by Cydhra** [Cydhra/Technocracy#55]
The following issues occur, when the mod is played on a remote server:

- [x] GUIs cannot be opened, as their `Container`s are created alongside client-side `GuiContainer`s
- [x] Client crashes on uninitialized lateinit when changing tabs in GUI of centrifuge
- [x] Multilayered textures create problems. See the ores for example. It seems to only affect textures that are loaded from minecraft
- [x] Client (and Server?) crash when using blocks from heat exchanger.
- [x] Astronautics tries to setup the wrapped world provider and the custom sky renderer server-side, which crashes

More issues may be discovered later. This issues tracks them.

**Comment by Pokemonplatin** [comment]
cacd44e fixed the guis

**Comment by Cydhra** [comment]
Now, when accessing GUIs (confirmed in singleplayer), and switching to the side config tab, the client crashes:

```
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property containerSlot has not been initialized
	at net.cydhra.technocracy.foundation.client.gui.components.slot.TCSlotIO.setEnabled(TCSlotIO.kt:70) ~[TCSlotIO.class:?]
	at net.cydhra.technocracy.foundation.client.gui.TCGui.mouseClicked(TCGui.kt:202) ~[TCGui.class:?]
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:611) ~[GuiScreen.class:?]
	at net.cydhra.technocracy.foundation.client.gui.TCGui.handleMouseInput(TCGui.kt:180) ~[TCGui.class:?]
```

**Comment by Pokemonplatin** [comment]
> Now, when accessing GUIs (confirmed in singleplayer), and switching to the side config tab, the client crashes:
> 
> ```
> Caused by: kotlin.UninitializedPropertyAccessException: lateinit property containerSlot has not been initialized
> 	at net.cydhra.technocracy.foundation.client.gui.components.slot.TCSlotIO.setEnabled(TCSlotIO.kt:70) ~[TCSlotIO.class:?]
> 	at net.cydhra.technocracy.foundation.client.gui.TCGui.mouseClicked(TCGui.kt:202) ~[TCGui.class:?]
> 	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:611) ~[GuiScreen.class:?]
> 	at net.cydhra.technocracy.foundation.client.gui.TCGui.handleMouseInput(TCGui.kt:180) ~[TCGui.class:?]
> ```

fixed with 72afd9c

**Comment by Pokemonplatin** [comment]
Multilayered textures now work again b2e160f

**Comment by Cydhra** [comment]
83bd907 fixed the issue with heat exchangers and f9482ab fixed a server-side issue with many multiblock blocks.

**Comment by Cydhra** [comment]
When shift clicking items (tested with iron ingots) into machines (tested with compactor). InventoryTweaks and MouseTweaks are present on this crash.

```
java.lang.AbstractMethodError: net.cydhra.technocracy.foundation.client.gui.container.components.SlotComponent.isEnabled()Z
	at net.cydhra.technocracy.foundation.client.gui.container.TCContainer$transferStackInSlot$guiSlots$2.test(TCContainer.kt:56)
	at net.cydhra.technocracy.foundation.client.gui.container.TCContainer$transferStackInSlot$guiSlots$2.test(TCContainer.kt:14)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:576)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:255)
	at java.util.stream.IntPipeline.toArray(IntPipeline.java:502)
	at kotlin.streams.jdk8.StreamsKt.toList(Streams.kt:66)
	at net.cydhra.technocracy.foundation.client.gui.container.TCContainer.func_82846_b(TCContainer.kt:56)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:246)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at net.cydhra.technocracy.foundation.client.gui.TCGui.func_73864_a(TCGui.kt:184)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.cydhra.technocracy.foundation.client.gui.TCGui.func_146274_d(TCGui.kt:180)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Cydhra** [comment]
All tracked issues resolved. Since the mod is now at least functioning on servers without immediate crashes, further issues shall be reported one by one
