### ISSUE TITLE
Tracking: Balancing

### ISSUE THREAD

**Issue by Cydhra** [Cydhra/Technocracy#56]
Just dump balancing-related stuff in here.

- [ ] Too much copper
- [x] Too much chrysotile
- [ ] Make lead more blue to make it more easy to spot and tin lighter or another tone
