### ISSUE TITLE
Side configs

### ISSUE THREAD

**Issue by Pokemonplatin** [Cydhra/Technocracy#57]
The side config is working but still needs some improvements.
For example fluids are currently not rendered and the depth is not properly used

- [x] Fix rendering of Tileentitys
- [x] The machine is rotated wrong if not facing north
- [ ] There is currently no way to configure a component that is input and output
- [ ] Fix the colors, they are not very color blind friendly right now
- [x] Fix that if a block infront of the camera gets transparent it does not allow the blocks behind it to be seen
- [x] Small or dark blocks are hard to see 
- [x] For some reason Beacons and Skulls are rendered wrong

**Comment by Pokemonplatin** [comment]
Fixed the rendering of the tile entitys by 9a8a9a9

**Comment by Pokemonplatin** [comment]
Fixed rotation and transparency by 1e432a6

**Comment by Cydhra** [comment]
When a capability in the machine is both INPUT and OUTPUT, the side config will only let you configure an input
