### ISSUE TITLE
Skylight Calculation of Saline

### ISSUE THREAD

**Issue by Cydhra** [Cydhra/Technocracy#67]
As mentioned in #66 the skylight calculation of the saline MBS does not work, yet.

- ~~[ ] Why does the function for skylight return 0 for all blocks, even when skylight is clearly different at that position~~
- [x] Fix Saline Blocks being transparent for light
- [ ] #71
- [ ] Write an update algorithm that schedules checks of skylight calculation for some tiles of some MB structures in the world (so not all structures are updated simultaneously, thus avoiding lag spikes)
- [ ] Multiply the skylight multiplier to the base conversion rate of the MBS

**Comment by tth05** [comment]
Regarding the first point: The problem where the skylight was 0 can actually be fixed by using `World#getLightFor` and incrementing the y-position by 1.
The problem that remains is that the Saline Wall and Saline Heated Wall blocks do not block light, which leads to incorrect light levels when placing blocks above the structure.

**Comment by Pokemonplatin** [comment]
fixed light opacity by 7fef4d4

**Comment by Cydhra** [comment]
To be replaced by modular multiblock for simplicity
