### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by Cydhra** [Cydhra/Technocracy#7]
This is a tracking issue for all mod GUI. Proposals, discussion and progress are documented here. The GUI has been worked on in the past, but it requires a lot more work.

- [x] Currently all GUIs are generated automatically for machines. While this is favorable for basic machines, complex ones may require manual gui setup. A simple builder interface (maybe using a Kotlin DSL) to create a gui with the components available, should be implemented.

- [x] The GUI does need bidirectional synchronization with the server. Changes made in GUI need to be sent to the server, machine contents and progress needs to be sent to the client. Further discussion and details required

- [x] For user experience a more detailed and fancy GUI should be considered. Currently all compoents look very basic and serve their purpose, but additional textures should be considered. This is especially the case for fill-meters like for energy and fluids. Fluids should be rendered using the respective fluid texture (sync required). Progress bars could be individualized for different machines.

- [x] Display side configs in a convenient and intuitive way. Discussion about details is required.

- [x] Shift clicking is to be implemented

- [x] Render additive components differently

- [x] Add a component to display text and stats of a (multiblock-) machine. A normal label could be used, but a more sophisticated solution with better formatting options is preferable

- [x] Heat storage component

**Comment by deftk** [comment]
Fluid textures and colors are now rendered (currently with placeholder fluid), texture for RedstoneModeControl was added, ToolTips appear now and show more details (f.e. stored Energy; not tested for slots because of missing sync).

**Comment by deftk** [comment]
Textures for EnergyMeter and FluidMeter were added (might be replaced later). GUIs for MultiBlocks were added (can only be shown by clicking at the controller block)

**Comment by deftk** [comment]
Torch Textures for the RedstoneMode Control  were added. A critical bug affecting the EnergyMeter was fixed (didn't render if current energy was 0).

**Comment by deftk** [comment]
Component for progress was added. Several bugs affecting the item slots were fixed.
Gui Slots should be fully functional now.

A strange bug appeared (not solved yet): Sometimes progress is already synced with the server, even if there is no sync system for components yet. After you restart the client, the bug appears usually 2 to 3 times and disappears.

**Comment by deftk** [comment]
Components are synced with the server.

**Comment by Cydhra** [comment]
I added a bullet point for shift clicking as it isn't done yet.
Syncing requires more testing, but the server->client seems to work properly. Client->Server must still be done, afaik?

**Comment by Cydhra** [comment]
For machines that is, multiblocks do not sync, yet.

**Comment by deftk** [comment]
Multiblock sync already finished (new commit), will be in a later pull request.

**Comment by deftk** [comment]
Current state (including #33 ):
Bidirectional sync is hopefully finished
A simple builder interface for machines to create & add its own custom tabs is available
More advanced textures were added (for EnergyMeter, FluidMeter and RedstoneModeControl)
FluidMeter draws fluids with their color & animated fluid texture

**Comment by Cydhra** [comment]
How is the creation of custom GUI tabs working? Can you explain in a quick example?

**Comment by deftk** [comment]
In TileEntityAlloySmeltery and TileEntityRefineryController is already an example

**Comment by Cydhra** [comment]
This might require some more work, but I guess not now, otherwise Beta is never gonna happen.

**Comment by Cydhra** [comment]
About the side configs: This cannot be resolved until conduits are ready, so dont worry about that for now. However this means that there is just the shift-issue and iteration on graphics remaining (we should move the latter into QA).
If you could fix the shift-issue that would be awesome, and then I think until conduits are ready, only JEI integration is the GUI related stuff remaining.

**Comment by Cydhra** [comment]
I added #36 so GUI refinement is no longer a goal of this issue

**Comment by Cydhra** [comment]
We need a way to chose different rendering methods for the same component. Example:

A machine with 2 fluid-components and one inventory-component. There is 1 input fluid and 1 output slot. Those shall be rendered normally. However, the third fluid input is marked (in some way) as an "additive" and thus shall be rendered differently to inform the player about the different requirement.
A simple example in-game is the polymerization chamber, that has an "additive input" for silica. It shall be rendered with a thinner component either left of the energy component, a tiny bar at the progress component or maybe a horizontal bar beneath everything else.

Edit: this was replaced through the system of attaching sub-guis to the left side of the main gui (for upgrades). This got rid of the need for other render modes (for now). If a specific one is desired at some point, just make an additional component for it and override autogeneration of the gui

**Comment by Cydhra** [comment]
Updating redstone mode from GUI is not always (in my tests only the first time) synced with the server. I was not able to cycle to "LOW"
However, sometimes the correct mode is shown on client, which is confusing.
I think the correct mode is not shown on client if the block receives a sync packet from the server anyway, e.g. when it is processing items thus updating progress.
This begs the question, why does updating progress also updates redstone mode. Isn't this unecessary network traffic?

Edit: fixed by 6138cb6e780dda063c2b20b19c9e58887a1e5fd5

**Comment by Cydhra** [comment]
Another issue is with the energy bar: WAILA and TOP integration correctly sync energy to the client, however the GUI itself does not. Energy is only updated when another update happens (like switching items, progress bar etc).
I think that this may be related to an attempt to reduce traffic by joining progress and energy into a single package, however if no progress happens, no packet is sent at all. Bulk-updates are fine and the number of packets sent should be reduced in favor of few large packets. However, if only a single datum changes, it must be sent anyway.

Edit: done

**Comment by Cydhra** [comment]
Another bug:
If a gui has more than one tab with inventory slots, it will add all slots of all tabs initially to the first tab and you have to switch tabs to clear them out.
Check Alloy Smeltery of current master branch to see issue happening.

Edit: fixed by  cf869a6

**Comment by Cydhra** [comment]
Feature Request:

To conveniently display stats and information about machines or multiblocks, a component should be added that supports auto-text-formatting. Formatting refers to auto-line-wrapping or tabular listing (for example to display speed-up multipliers in the machine upgrade tab)

Edit: done

**Comment by Cydhra** [comment]
The GUIs are functional, components are implemented, and side configs are implemented.
Most GUIs are still autogenerated which will be changed in the future probably. However, this is not necessary for the beta release.
There is still some stuff to do, but it is not strongly related to this issue. Side configs have still bugs (though they are WIP currently), some components could use some more work, etc.
Overall, the gui works and can be released into beta. Therefore I'll close this issue.
