### ISSUE TITLE
Render Dyson Sphere

### ISSUE THREAD

**Issue by Cydhra** [Cydhra/Technocracy#70]
- [ ] 3D model dyson sphere
   - [ ] sun model
   - [ ] dyson sphere stage models
- [ ] render stages to texture
- [ ] render stages into skybox according to dyson sphere progress

**Comment by Flaflo** [comment]
Please more info, thanks
