### ISSUE TITLE
Replace Zerocore Saline Structure with Our Structure System

### ISSUE THREAD

**Issue by Cydhra** [Cydhra/Technocracy#71]
The Saline is currently implemented using Zerocore. It should be implemented using the structure template system currently used for the rockets in astronautics. It is ought to be more flexible and reduces our dependency on Zerocore, which comes with severe limitations.

- [ ] create the necessary templates
- [ ] implement the modular verification
- [ ] implement the necessary physics calculations
- [ ] implement the recipes
