### ISSUE TITLE
JEI integration

### ISSUE THREAD

**Issue by Cydhra** [Cydhra/Technocracy#8]
Extensive JEI integration is required. This is considered mandatory for a release candidate, since players need intuitive and easy access to recipes and available items.

- [x] animated progress bars
- ~~[ ] clickable progress bars (to show recipes of machine)~~
- [x] fix autogeneration using the names of registered components. Those names are not standardized and shall not be
- [x] fluid meter component rendered wrong
- [ ] fluid meter of refinery is rendered wrong

**Comment by Cydhra** [comment]
Most GUIs are implemented/generated and whatnot.
Now we can start display recipes in JEI using the available GUIs.

**Comment by Cydhra** [comment]
It would be cool to animated the progress bar in the GUIs when recipes are displayed. The bar should just fill from 0 to 100% and then reset to 0.

**Comment by Cydhra** [comment]
Bug: Using `IAdvancedGuiHandler` it should be possible to tell JEI, that its items must be moved away from our tab-bar in our machine GUIs. This was implemented as part of the integration in `TCGuiHandler` and registered within the JEI plugin.
However, the handler is never called and thus doesn't actually do anything.
Find out why this is and fix it, so the JEI item list is not rendered above our tabs.

**Comment by Cydhra** [comment]
ac60e331e22709b085e058773070ef4c6fc6c5de fixed issue https://github.com/Cydhra/Technocracy/issues/8#issuecomment-569302051

**Comment by Cydhra** [comment]
In the industrial refinery, recipes show the output items as input items and input items aren't shown.

**Comment by Cydhra** [comment]
Clickable areas to display machine recipes aren't really possible with our approach to GUIs, because the areas are hardcoded per GUI class, and our GUIs are too flexible for that. Since we can still view all recipes by using the "Show Usage" function on the machines, we accept that for now
